site_name: Learn Ubuntu
site_url: https://www.patashale.in/learn-ubuntu/
site_author: Patashale™
site_description: Learn everything about Ubuntu here at Patashale™.
repo_url: https://github.com/patashale/learn-ubuntu
repo_name: patashale/learn-ubuntu
theme:
  name: material
  language: en
  logo: assets/ubuntu-logo.svg
  favicon: assets/ubuntu-logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        background_color: "#741113"
        
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/patashale
      name: Patashale™ on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale™ on GitHub
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@patashale
      name: Patashale™ on YouTube

nav:
  - Home: index.md
  - How-to:
    - Overview: en/how-to/overview.md
    - Visual Studio Code: en/how-to/visual-studio-code.md

copyright: Copyright &copy; 2023 Patashale™
